apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0b9ec29434141f5b1
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: unir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 5Gi
  storageClassName: manual  
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi